### ISSUE TITLE
unlikely function name in UMRAD

### ISSUE THREAD

**Issue by akiledal** [Geo-omics/UMRAD#1]
THIAMINEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE EEEEEEEEEEE DIPHOSPHATE-BINDING PROTEIN

see https://greatlakesomics.org/data/functionname/2923217/

**Comment by akiledal** [comment]
Definitely doesn't look right, but [it comes from UniRef that way](https://www.uniprot.org/uniprotkb?query=THIAMINEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE+EEEEEEEEEEE+DIPHOSPHATE-BINDING+PROTEIN). Not sure how much we want to get in the business of cleaning up their annotations.

**Comment by akiledal** [comment]
@robert102 can we close this?

**Comment by akiledal** [comment]
@robert102 you said the other day you still consider this an issue we need to address?

**Comment by robert102** [comment]
The names appear in the downloaded uniprot data for A0A6A4HD87 and A0A6A4HM81 and in the uniref100 fasta header for UniRef100_A0A6A4HM81.  There seems to be no corresponding fasta record for A0A6A4HD87 !?!

**Comment by akiledal** [comment]
We talked about this, but making a note that I see a fasta record in UMRAD/Universal_Microbiomics_Alignment_Database/uniref100.fasta.gz, but it sounds like you were searching in the split fasta files or a product of them.
